baseURL = "https://blog.raph.ws/"
languageCode = "en-us"
title = "Raph's Blog"
theme = "kiera"

[permalinks]
  post = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "https://raph.ws"
    weight = -110
