baseURL = "https://blog.raph.ws/"
languageCode = "en-us"
title = "Raph's Blog"
theme = "kiera"

[params]
  author = "Raphael Haddad"
  description = "Raph's blog"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
  post = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "https://raph.ws"
    weight = -110
